//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bdCICAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMBX
    {
        public long CMBX_IDENTITY { get; set; }
        public string DESCRIPCION { get; set; }
    }
}
